#!/usr/bin/env bash
# Generates .agents/config.toml (project-level Codex config) and ensures
# .codex/config.toml symlinks to it.
#
# Run from anywhere inside the repo — uses the script's own location to
# anchor paths, so it's always correct regardless of CWD.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$SCRIPT_DIR"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$AGENTS_DIR/config.toml"
SYMLINK="$PROJECT_DIR/.codex/config.toml"

# ── Generate config.toml ────────────────────────────────────────────────────
cat > "$CONFIG_FILE" <<'TOML'
# Project-level Codex configuration for numis.
# Generated by .agents/generate-codex-config.sh — edit the script, not this file.

git_commit_coauthor = "Codex <noreply@openai.com>"

# Task Master AI — stdio MCP server (project-scoped, mirrors .mcp.json for Claude Code)
[mcp_servers.task-master-ai]
command = "npx"
args = ["-y", "task-master-ai"]
TOML

echo "✓ Written $CONFIG_FILE"

# ── Create / update symlink ─────────────────────────────────────────────────
# Relative path so the symlink is portable if the repo is moved
RELATIVE_TARGET="../.agents/config.toml"

if [ -L "$SYMLINK" ]; then
  CURRENT_TARGET="$(readlink "$SYMLINK")"
  if [ "$CURRENT_TARGET" = "$RELATIVE_TARGET" ]; then
    echo "✓ Symlink already correct: $SYMLINK -> $RELATIVE_TARGET"
  else
    ln -sf "$RELATIVE_TARGET" "$SYMLINK"
    echo "✓ Updated symlink: $SYMLINK -> $RELATIVE_TARGET (was -> $CURRENT_TARGET)"
  fi
elif [ -e "$SYMLINK" ]; then
  echo "✗ $SYMLINK exists but is not a symlink — remove it manually and re-run."
  exit 1
else
  ln -s "$RELATIVE_TARGET" "$SYMLINK"
  echo "✓ Created symlink: $SYMLINK -> $RELATIVE_TARGET"
fi
